upgrade libboost to 1.83 to fix libswsscommon download (#170)
upgrade the libboost version to 1.83 to fix the following error:

make -C libcswsscommon
make[2]: Entering directory '/src/rest/libcswsscommon'
g++ -g -std=c++11 -Iinclude -I/common -I/usr/include/swss -c src/dbconnector.cpp -o src/dbconnector.o
src/dbconnector.cpp:2:10: fatal error: dbconnector.h: No such file or directory
    2 | #include <dbconnector.h>
      |          ^~~~~~~~~~~~~~~
This file can not be found because libswsscommon-dev_1.0.0_amd64.deb is not correctly set up, which is caused by

dpkg: dependency problems prevent configuration of libswsscommon:
#9 0.480  libswsscommon depends on libboost-serialization1.83.0 (>= 1.83.0); however:
#9 0.480   Package libboost-serialization1.83.0 is not installed.
This issue occurred after Dec 15 2025 due to the package